In [6]:
#/archive dataset from Kaggle: https://www.kaggle.com/datasets/bikashkundu/can-hcrl-otids
#/road dataset: https://zenodo.org/records/10462796

In [ ]:
import pandas as pd

In [ ]:
CAN_HCRL_OTIDS_B = pd.read_csv("archive/CAN_HCRL_OTIDS_B.csv")
CAN_HCRL_OTIDS_UB = pd.read_csv("archive/CAN_HCRL_OTIDS_UB.csv")
dataset = pd.read_csv("archive/dataset.csv")
attack_free = pd.read_csv("archive/dataset1.csv") #dataset1.csv contains all records of Attack_free_dataset.txt with target column as 0.

dataset2 = pd.read_csv("archive/dataset2.csv") #dataset2.csv contains all records of Dos_attack_dataset.txt with target column as 1.
dataset3= pd.read_csv("archive/dataset3.csv")

CAN_HCRL_OTIDS_B.head()

             TS   ID1  DLC0  DLC1  DLC2  DLC3  DLC4  DLC5  DLC6  DLC7  target
0  3.850719e+02   339     0   128    16   255     0   255   144    30       0
1  1.481193e+09  1349   218    14     0   138    42     0    45     0       3
2  9.061502e+01  1266     0     0    64    56     0     0     0   165       0
3  1.481193e+09  1200     0     0     0     0     0     0     0     0       3
4  1.481193e+09  1087    16    80   100   255    81    88     9     0       3

In [5]:
CAN_HCRL_OTIDS_UB.head()
dataset.head()

         TS   ID1  ID0  LEN DLC0 DLC1 DLC2 DLC3 DLC4 DLC5 DLC6 DLC7  target
0  0.000000  0316    0    8   05   20   ea   0a   20   1a   00   7f       0
1  0.000224  0329    0    8   d7   a7   7f   8c   11   2f   00   10       0
2  0.000462  0080    0    8   00   17   ea   0a   20   1a   20   43       0
3  0.000704  0081    0    8   7f   84   60   00   00   00   00   53       0
4  0.000878  0120    0    4   00   00   00   00  NaN  NaN  NaN  NaN       0

In [ ]:
data